#!/usr/bin/env bash
# Display message indefinitely and handle SIGTERM signal

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal
trap handle_sigterm TERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
